### ISSUE TITLE
Cant build the project 

### ISSUE THREAD

**Issue by haiweiwang73** [linkedin/parseq#219]
Ran the command in the readme for the trace tool... can't event build, the jar on repo didn't include the manifest file as well. stuck!

Getting 
```
Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:642)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:461)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:361)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:626)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 29 more
```

Can someone update the readme ?

**Comment by bolobobo** [comment]
@haiweiwang73 To make things clear, you said you can not build the whole project Or you can't start the parseq-tracevis-server by following the https://github.com/linkedin/parseq/blob/master/subprojects/parseq-tracevis-server/README.md ?

**Comment by haiweiwang73** [comment]
@bolobobo I tried both, clone the repo and try the command ./gradlew build under the parseq-tracevis-server, its complaining theres no gradlew file. Tried to build the whole project, got the issue above.

**Comment by bolobobo** [comment]
@haiweiwang73 For the build command, you should run the `./gradlew build` in the root directory, otherwise it would complain there's no gradlew file. For the exception you got, my hunch is that you haven't set the ssl correctly. Have tried to fresh checkout the project and do not set up any ssl? Actually, you don't need to set up SSL if you only need a http server. Just fresh checkout and try `./gradlew runTracevisServer`.

**Comment by haiweiwang73** [comment]
Got it, thanks. Will try it out. I have couple more question about how the onFailure works and exception handling. Is there a email address that I can send you some of the code I'm working on and get some opinion from you ?

**Comment by bolobobo** [comment]
You can just open another issue. So my team member can also view it and give you some suggestions.

**Comment by haiweiwang73** [comment]
After I ran the command, ./gradlew runTracevisServer , this is what I get 
```
928 error Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
928 error Make sure you have the latest version of node.js and npm installed.
928 error If you do, this is most likely a problem with the contextify package,
928 error not with npm itself.
928 error Tell the author that this fails on your system:
928 error     node-gyp rebuild
928 error You can get information on how to open an issue for this project with:
928 error     npm bugs contextify
928 error Or if that isn't available, you can get their info via:
928 error     npm owner ls contextify
928 error There is likely additional logging output above.
929 verbose exit [ 1, true ]
```

**Comment by bolobobo** [comment]
I assumed you may see some errors about xcode in your log. 2 possible way to make it work:
-  Reinstall xcode by following: https://github.com/nodejs/node-gyp/issues/569 and then rebuild.
-  Update the version of d3: 1) delete the `parseq/subprojects/parseq-tracevis/node_modules` directory; 2) change the d3 version in `package.json` to `3.5.5`; 3) rebuild the whole project.
