### ISSUE TITLE
linkedin-agent-loader is not compatible with Java 11

### ISSUE THREAD

**Issue by arnoha** [linkedin/parseq#286]
linkedin-agent-loader is a deprecated project that `com.linkedin.parseq.lambda.ASMBasedTaskDescriptor` depends on. This pattern of loading agent is not recommended after Java 8 and, more specifically, the code as written today references HotSpot, making it incompatible with Java 11.

Example failure:
`    java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.LinuxAttachProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:258)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.list(VirtualMachine.java:144)
        at com.linkedin.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:80)
        at com.linkedin.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.linkedin.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:247)
        at com.linkedin.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
        at com.linkedin.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:153)
        at com.linkedin.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:104)
        at com.linkedin.parseq.lambda.ASMBasedTaskDescriptor.<clinit>(ASMBasedTaskDescriptor.java:53)`

**Comment by junchuanwang** [comment]
Have confirmed with the reporter that the newly released 5.1.0 solves the issue. Will close this now
