### ISSUE TITLE
GOT a NPE when use TraceUtil.getJsonTrace function

### ISSUE THREAD

**Issue by nancy1992** [linkedin/parseq#301]
I create a task which contains a subTask that runs fail in runtime.

my code is:
```
 engine.run(task);
 task.await();
 LOGGER.debug("JSON Trace:{}", TraceUtil.getJsonTrace(task));
```

I got NPE which is shown below
```
java.lang.NullPointerException: resultType must not be null
	at com.linkedin.parseq.internal.ArgumentUtil.requireNotNull(ArgumentUtil.java:28) ~[parseq-4.0.1.jar!/:?]
	at com.linkedin.parseq.trace.ShallowTraceImp.<init>(ShallowTraceImp.java:52) ~[parseq-4.0.1.jar!/:?]
	at com.linkedin.parseq.trace.ShallowTraceBuilder.build(ShallowTraceBuilder.java:215) ~[parseq-4.0.1.jar!/:?]
	at com.linkedin.parseq.trace.TraceBuilder.lambda$build$1(TraceBuilder.java:85) ~[parseq-4.0.1.jar!/:?]
	at com.linkedin.parseq.trace.TraceBuilder$$Lambda$1368/2113831684.apply(Unknown Source) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[?:1.8.0_45]
	at com.linkedin.parseq.trace.TraceBuilder.build(TraceBuilder.java:85) ~[parseq-4.0.1.jar!/:?]
	at com.linkedin.parseq.BaseTask.getTrace(BaseTask.java:292) ~[parseq-4.0.1.jar!/:?]
	at com.linkedin.parseq.trace.TraceUtil.getJsonTrace(TraceUtil.java:22) ~[parseq-4.0.1.jar!/:?]
```
From the stack ,I know the resultType of a task is null,but I don't know which task's resultType is null .
Who meets the same issue?Who can help me ?

**Comment by nancy1992** [comment]
Sorry , the issue appears in the product environment occasionally, and  cannot reappear stably,  now I am trying to reappear it in the test environment

**Comment by junchuanwang** [comment]
Hi @nancy1992  
I might have to close this as this is not reproducible. Meanwhile if you have issues feel free to reach out
