### ISSUE TITLE
CI Failure: TestContext.testCreateTimer

### ISSUE THREAD

**Issue by cpettitt** [linkedin/parseq#7]
Looks like an intermittent failure, found by Travis-CI. I suspect we may need to bump up the tolerance on the timeouts.

```
277   [testng] FAILED: testCreateTimer
278   [testng] java.lang.AssertionError: 
279   [testng] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
280   [testng] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
281   [testng] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
282   [testng] 	at com.linkedin.parseq.TestContext.testCreateTimer(TestContext.java:138)
283   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
284   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
285   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
286   [testng] 	at java.lang.reflect.Method.invoke(Method.java:601)
287   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
288   [testng] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
289   [testng] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
290   [testng] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
291   [testng] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
292   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
293   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:758)
294   [testng] 	at org.testng.TestRunner.run(TestRunner.java:613)
295   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
296   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
297   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
298   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
299   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
300   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
301   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)
302   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)
303   [testng] 	at org.testng.TestNG.run(TestNG.java:1007)
304   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1315)
305   [testng] 	at org.testng.TestNG.main(TestNG.java:1279)
```

**Comment by jodzga** [comment]
Did not observe this issue for a very long time, closing.
